import ITransport from "../Models/ITransport";

export const mockedTransports: ITransport[] = [
  {
    id: 0,
    id_trip: 35,
    name: "transport 1",
    description: "description",
    duration: 2,
    price: 0,
    attachment: [],
    departure: "dubai",
    destination: "france",
    used: 0,
    lat_from: 0,
    lat_to: 0,
    lng_from: 0,
    lng_to: 0,
  },
  {
    id: 2,
    id_trip: 35,
    name: "transport 2",
    description: "description",
    duration: 1,
    price: 0,
    attachment: [],
    departure: "dubai",
    destination: "france",
    used: 0,
    lat_from: 0,
    lat_to: 0,
    lng_from: 0,
    lng_to: 0,
  },
  {
    id: 3,
    id_trip: 35,
    name: "transport 3",
    description: "description",
    duration: 1,
    price: 0,
    attachment: [],
    departure: "dubai",
    destination: "france",
    used: 0,
    lat_from: 0,
    lat_to: 0,
    lng_from: 0,
    lng_to: 0,
  },
  {
    id: 4,
    id_trip: 35,
    name: "transport 4",
    description: "description",
    duration: 1,
    price: 0,
    attachment: [],
    departure: "dubai",
    destination: "france",
    used: 0,
    lat_from: 0,
    lat_to: 0,
    lng_from: 0,
    lng_to: 0,
  },
  {
    id: 5,
    id_trip: 35,
    name: "transport 5",
    description: "description",
    duration: 1,
    price: 0,
    attachment: [],
    departure: "dubai",
    destination: "france",
    used: 0,
    lat_from: 0,
    lat_to: 0,
    lng_from: 0,
    lng_to: 0,
  },
  {
    id: 6,
    id_trip: 35,
    name: "transport 6",
    description: "description",
    duration: 1,
    price: 0,
    attachment: [],
    departure: "dubai",
    destination: "france",
    used: 0,
    lat_from: 0,
    lat_to: 0,
    lng_from: 0,
    lng_to: 0,
  },
  {
    id: 7,
    id_trip: 35,
    name: "transport 7",
    description: "description",
    duration: 1,
    price: 0,
    attachment: [],
    departure: "dubai",
    destination: "france",
    used: 0,
    lat_from: 0,
    lat_to: 0,
    lng_from: 0,
    lng_to: 0,
  },
  {
    id: 8,
    id_trip: 35,
    name: "transport 8",
    description: "description",
    duration: 1,
    price: 0,
    attachment: [],
    departure: "dubai",
    destination: "france",
    used: 0,
    lat_from: 0,
    lat_to: 0,
    lng_from: 0,
    lng_to: 0,
  },
];
