import IAccomodation from "../Models/IAccomodation";

export const mockedAccomodations: IAccomodation[] = [
  {
    id: 0,
    id_trip: 35,
    name: "accomodation 1",
    description: "description",
    price: 0,
    location: "location",
    attachment: [],
    used: 0,
    checkin: "17h00",
    checkout: "10h00",
    lat: 0,
    lng: 0,
    city: null,
  },
  {
    id: 2,
    id_trip: 35,
    name: "accomodation 2",
    description: "description",
    price: 0,
    location: "location",
    attachment: [],
    used: 0,
    checkin: "17h00",
    checkout: "10h00",
    lat: 0,
    lng: 0,
    city: null,
  },
  {
    id: 3,
    id_trip: 35,
    name: "accomodation 3",
    description: "description",
    price: 0,
    location: "location",
    attachment: [],
    used: 0,
    checkin: "17h00",
    checkout: "10h00",
    lat: 0,
    lng: 0,
    city: null,
  },
];
