import ITransport from "../Models/ITransport";

export const mockedTransports: ITransport[] = [
  {
    id: 0,
    id_trip: 35,
    name: "transport 1",
    description: "description",
    duration: 2,
    price: 0,
    attachment: [],
    from: "dubai",
    to: "france",
    vehicule: "voiture",
    used: false,
  },
  {
    id: 2,
    id_trip: 35,
    name: "transport 2",
    description: "description",
    duration: 1,
    price: 0,
    attachment: [],
    from: "dubai",
    to: "france",
    vehicule: "voiture",
    used: false,
  },
  {
    id: 3,
    id_trip: 35,
    name: "transport 3",
    description: "description",
    duration: 1,
    price: 0,
    attachment: [],
    from: "dubai",
    to: "france",
    vehicule: "voiture",
    used: false,
  },
  {
    id: 4,
    id_trip: 35,
    name: "transport 4",
    description: "description",
    duration: 1,
    price: 0,
    attachment: [],
    from: "dubai",
    to: "france",
    vehicule: "voiture",
    used: false,
  },
  {
    id: 5,
    id_trip: 35,
    name: "transport 5",
    description: "description",
    duration: 1,
    price: 0,
    attachment: [],
    from: "dubai",
    to: "france",
    vehicule: "voiture",
    used: false,
  },
  {
    id: 6,
    id_trip: 35,
    name: "transport 6",
    description: "description",
    duration: 1,
    price: 0,
    attachment: [],
    from: "dubai",
    to: "france",
    vehicule: "voiture",
    used: false,
  },
  {
    id: 7,
    id_trip: 35,
    name: "transport 7",
    description: "description",
    duration: 1,
    price: 0,
    attachment: [],
    from: "dubai",
    to: "france",
    vehicule: "voiture",
    used: false,
  },
  {
    id: 8,
    id_trip: 35,
    name: "transport 8",
    description: "description",
    duration: 1,
    price: 0,
    attachment: [],
    from: "dubai",
    to: "france",
    vehicule: "voiture",
    used: false,
  },
];
