import IActivity from "../Models/IActivity";

export const mockedActivities: IActivity[] = [
  {
    id: 0,
    id_trip: 35,
    name: "activity 1",
    description: "description",
    duration: 8,
    price: 0,
    pleasure: 0,
    location: "location",
    attachment: [],
    contraint: "contraint",
    used: 0,
    lat: 0,
    lng: 0,
    city: null,
  },
  {
    id: 2,
    id_trip: 35,
    name: "activity 2",
    description: "description",
    duration: 0.25,
    price: 0,
    pleasure: 0,
    location: "location",
    attachment: [],
    contraint: "contraint",
    used: 0,
    lat: 0,
    lng: 0,
    city: null,
  },
  {
    id: 3,
    id_trip: 35,
    name: "activity 3",
    description: "description",
    duration: 0.5,
    price: 0,
    pleasure: 0,
    location: "location",
    attachment: [],
    contraint: "contraint",
    used: 0,
    lat: 0,
    lng: 0,
    city: null,
  },
  {
    id: 4,
    id_trip: 35,
    name: "activity 4",
    description: "description",
    duration: 0.75,
    price: 0,
    pleasure: 0,
    location: "location",
    attachment: [],
    contraint: "contraint",
    used: 0,
    lat: 0,
    lng: 0,
    city: null,
  },
  {
    id: 5,
    id_trip: 35,
    name: "activity 5",
    description: "description",
    duration: 1,
    price: 0,
    pleasure: 0,
    location: "location",
    attachment: [],
    contraint: "contraint",
    used: 0,
    lat: 0,
    lng: 0,
    city: null,
  },
  {
    id: 6,
    id_trip: 35,
    name: "activity 6",
    description: "description",
    duration: 1,
    price: 0,
    pleasure: 0,
    location: "location",
    attachment: [],
    contraint: "contraint",
    used: 0,
    lat: 0,
    lng: 0,
    city: null,
  },
  {
    id: 7,
    id_trip: 35,
    name: "activity 7",
    description: "description",
    duration: 1,
    price: 0,
    pleasure: 0,
    location: "location",
    attachment: [],
    contraint: "contraint",
    used: 0,
    lat: 0,
    lng: 0,
    city: null,
  },
  {
    id: 8,
    id_trip: 35,
    name: "activity 8",
    description: "description",
    duration: 1,
    price: 0,
    pleasure: 0,
    location: "location",
    attachment: [],
    contraint: "contraint",
    used: 0,
    lat: 0,
    lng: 0,
    city: null,
  },
];
